### ISSUE TITLE
add metadata creation to necsc data release

### ISSUE THREAD

**Issue by jordansread** [USGS-R/necsc-lake-modeling#88]
This is for the tri-state release

@lawinslow can you help me anticipate the structure of the outputs?

``` YAML
Release:
   - Core temperature metrics: ["NLDAS","ACCESS","MRI","MIROC","GFDL","IPSL"]
   - Model configuration input: ["NLDAS","ACCESS","MRI","MIROC","GFDL","IPSL"]
   - Raw water temperature: ["NLDAS","ACCESS","MRI","MIROC","GFDL","IPSL"]
```

each of these will have metadata associated with it, so for example, 

release.xml, core.xml, core_nldas.xml, config.xml, config_nldas.xml, raw.xml, raw_nldas.xml and so on (ignore my name choices), resulting in 22 `xml` files? is that correct? (not each parent item will have an xml file based on my assumptions.

**Comment by lawinslow** [comment]
Here is where RC2 is being built
https://www.sciencebase.gov/catalog/item/57c5c793e4b0f2f0cebdaa4d

NLDAS is up there now. 

Based on our earlier conversation, we were trying to consolidate the outputs into 3 categories so that only 3 (or 4 if we add a shapefile) metadata files will need to be created. So I'm expecting it to look like
`release.xml, thermal.xml, config.xml,  raw.xml`. I left in `release.xml` as that will probably be the top-level item. This structure works if we in fact can describe several identical files with the same metadata document. 

The only question in my mind is with the `raw.xml` as those outputs are large and may be easily stored all associated with one SBitem.

**Comment by jordansread** [comment]
Ok, sounds great to me.

**Comment by jordansread** [comment]
I am going to include `lakes.xml` in there as a placeholder for the spatial data for the time being. I am assuming we are going to want to include something that will hold the lake locations (probably NHD subset)?

**Comment by lawinslow** [comment]
Yeah, sounds good. NHD subset will almost definitely be included.

**Comment by jordansread** [comment]
Here is a start on the structure of that: 

https://github.com/jread-usgs/necsc-lake-modeling/blob/master/remake_necsc_release.yml

**Comment by lawinslow** [comment]
Just added lakes:https://www.sciencebase.gov/catalog/item/57d97341e4b090824ffb0e6f

Should we have lake attributes like zmax/secchi/landcover/canopy attached, or no? Thoughts?

**Comment by jordansread** [comment]
``` YAML
target_default: necsc_release


packages:
  - yaml
  - xml2
  - whisker
  - rgdal
  - httr
  - sbtools
  - rgeos
  - dataRetrieval

sources:
  - scripts/create_FGDC_template.R
  - scripts/render_FGDC_metadata.R
  - scripts/post_data_release.R
  - scripts/extract_metadata.R

targets:
  necsc_release:
    depends: 
      - necsc_release/release.xml
      - necsc_release/thermal.xml
      - necsc_release/config.xml
      - necsc_release/raw.xml
      - necsc_release/lakes.xml



  necsc_release/FGDC_template.mustache:
    command: create_FGDC_template(target_name)

  attribute.table:
    command: create_release_attributes()

  release.text:
    command: yaml.load_file("necsc_release/text_release.yaml")

  thermal.text:
    command: yaml.load_file("necsc_release/text_thermal.yaml")

  config.text:
    command: yaml.load_file("necsc_release/text_config.yaml")

  raw.text:
    command: yaml.load_file("necsc_release/raw_config.yaml")

  lakes.text:
    command: yaml.load_file("necsc_release/lakes_config.yaml")

  lakes.metadata:
    command: extract_spatial_metadata(lakes_shapefile)


  necsc_release/release.xml:
    command: render_FGDC_metadata("necsc_release/FGDC_template.mustache", target_name, release.text, lakes.metadata) 
```
